### ISSUE TITLE
sign_out Error

### ISSUE THREAD

**Issue by oliverriechert** [8bitpal/hackful#57]
Chrome Bowser -  JavaScript is OFF

After the sign_out

 I get an error message:

RuntimeError in UsersController#show

Called id for nil, which would mistakenly be 4 -- if you really wanted the id of nil, use object_id
Rails.root: /u/apps/hackful/releases/20130215174212

app/controllers/users_controller.rb:7:in `show'
actionpack (3.1.10) lib/action_controller/metal/implicit_render.rb:4:in`send_action'
actionpack (3.1.10) lib/abstract_controller/base.rb:167:in `process_action'
actionpack (3.1.10) lib/action_controller/metal/rendering.rb:10:in`process_action'
actionpack (3.1.10) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
activesupport (3.1.10) lib/active_support/callbacks.rb:425:in`_run__801964955__process_action__368434572__callbacks'
activesupport (3.1.10) lib/active_support/callbacks.rb:386:in `_run_process_action_callbacks'
activesupport (3.1.10) lib/active_support/callbacks.rb:81:in`run_callbacks'
actionpack (3.1.10) lib/abstract_controller/callbacks.rb:17:in `process_action'
actionpack (3.1.10) lib/action_controller/metal/rescue.rb:17:in`process_action'
actionpack (3.1.10) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
activesupport (3.1.10) lib/active_support/notifications.rb:53:in`block in instrument'
activesupport (3.1.10) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (3.1.10) lib/active_support/notifications.rb:53:in`instrument'
actionpack (3.1.10) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
actionpack (3.1.10) lib/action_controller/metal/params_wrapper.rb:201:in`process_action'
activerecord (3.1.10) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (3.1.10) lib/abstract_controller/base.rb:121:in`process'
actionpack (3.1.10) lib/abstract_controller/rendering.rb:45:in `process'
actionpack (3.1.10) lib/action_controller/metal.rb:193:in`dispatch'
actionpack (3.1.10) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
actionpack (3.1.10) lib/action_controller/metal.rb:236:in`block in action'
actionpack (3.1.10) lib/action_dispatch/routing/route_set.rb:71:in `call'
actionpack (3.1.10) lib/action_dispatch/routing/route_set.rb:71:in`dispatch'
actionpack (3.1.10) lib/action_dispatch/routing/route_set.rb:35:in `call'
rack-mount (0.8.3) lib/rack/mount/route_set.rb:152:in`block in call'
rack-mount (0.8.3) lib/rack/mount/code_generation.rb:96:in `block in recognize'
rack-mount (0.8.3) lib/rack/mount/code_generation.rb:103:in`optimized_each'
rack-mount (0.8.3) lib/rack/mount/code_generation.rb:95:in `recognize'
rack-mount (0.8.3) lib/rack/mount/route_set.rb:141:in`call'
actionpack (3.1.10) lib/action_dispatch/routing/route_set.rb:538:in `call'
warden (1.2.1) lib/warden/manager.rb:35:in`block in call'
warden (1.2.1) lib/warden/manager.rb:34:in `catch'
warden (1.2.1) lib/warden/manager.rb:34:in`call'
actionpack (3.1.10) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
rack (1.3.10) lib/rack/etag.rb:23:in`call'
rack (1.3.10) lib/rack/conditionalget.rb:25:in `call'
actionpack (3.1.10) lib/action_dispatch/middleware/head.rb:14:in`call'
actionpack (3.1.10) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
actionpack (3.1.10) lib/action_dispatch/middleware/flash.rb:243:in`call'
rack (1.3.10) lib/rack/session/abstract/id.rb:195:in `context'
rack (1.3.10) lib/rack/session/abstract/id.rb:190:in`call'
actionpack (3.1.10) lib/action_dispatch/middleware/cookies.rb:331:in `call'
activerecord (3.1.10) lib/active_record/query_cache.rb:64:in`call'
activerecord (3.1.10) lib/active_record/connection_adapters/abstract/connection_pool.rb:477:in `call'
actionpack (3.1.10) lib/action_dispatch/middleware/callbacks.rb:29:in`block in call'
activesupport (3.1.10) lib/active_support/callbacks.rb:392:in `_run_call_callbacks'
activesupport (3.1.10) lib/active_support/callbacks.rb:81:in`run_callbacks'
actionpack (3.1.10) lib/action_dispatch/middleware/callbacks.rb:28:in `call'
actionpack (3.1.10) lib/action_dispatch/middleware/reloader.rb:68:in`call'
rack (1.3.10) lib/rack/sendfile.rb:101:in `call'
actionpack (3.1.10) lib/action_dispatch/middleware/remote_ip.rb:48:in`call'
actionpack (3.1.10) lib/action_dispatch/middleware/show_exceptions.rb:47:in `call'
railties (3.1.10) lib/rails/rack/logger.rb:13:in`call'
rack (1.3.10) lib/rack/methodoverride.rb:24:in `call'
rack (1.3.10) lib/rack/runtime.rb:17:in`call'
activesupport (3.1.10) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
rack (1.3.10) lib/rack/lock.rb:15:in`call'
actionpack (3.1.10) lib/action_dispatch/middleware/static.rb:61:in `call'
railties (3.1.10) lib/rails/engine.rb:456:in`call'
railties (3.1.10) lib/rails/application.rb:143:in `call'
railties (3.1.10) lib/rails/railtie/configurable.rb:30:in`method_missing'
passenger (3.0.11) lib/phusion_passenger/rack/request_handler.rb:96:in `process_request'
passenger (3.0.11) lib/phusion_passenger/abstract_request_handler.rb:513:in`accept_and_process_next_request'
passenger (3.0.11) lib/phusion_passenger/abstract_request_handler.rb:274:in `main_loop'
passenger (3.0.11) lib/phusion_passenger/rack/application_spawner.rb:206:in`start_request_handler'
passenger (3.0.11) lib/phusion_passenger/rack/application_spawner.rb:171:in `block in handle_spawn_application'
passenger (3.0.11) lib/phusion_passenger/utils.rb:479:in`safe_fork'
passenger (3.0.11) lib/phusion_passenger/rack/application_spawner.rb:166:in `handle_spawn_application'
passenger (3.0.11) lib/phusion_passenger/abstract_server.rb:357:in`server_main_loop'
passenger (3.0.11) lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
passenger (3.0.11) lib/phusion_passenger/abstract_server.rb:180:in`start'
passenger (3.0.11) lib/phusion_passenger/rack/application_spawner.rb:129:in `start'
passenger (3.0.11) lib/phusion_passenger/spawn_manager.rb:253:in`block (2 levels) in spawn_rack_application'
passenger (3.0.11) lib/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
passenger (3.0.11) lib/phusion_passenger/spawn_manager.rb:246:in`block in spawn_rack_application'
passenger (3.0.11) lib/phusion_passenger/abstract_server_collection.rb:82:in `block in synchronize'
<internal:prelude>:10:in`synchronize'
passenger (3.0.11) lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
passenger (3.0.11) lib/phusion_passenger/spawn_manager.rb:244:in`spawn_rack_application'
passenger (3.0.11) lib/phusion_passenger/spawn_manager.rb:137:in `spawn_application'
passenger (3.0.11) lib/phusion_passenger/spawn_manager.rb:275:in`handle_spawn_application'
passenger (3.0.11) lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
passenger (3.0.11) lib/phusion_passenger/abstract_server.rb:206:in`start_synchronously'
passenger (3.0.11) helper-scripts/passenger-spawn-server:99:in `<main>'

Request

Parameters:

{"has_one"=>:data_set,
 "id"=>"sign_out"}

HTTP_ACCEPT: "text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8"
HTTP_ACCEPT_CHARSET: "ISO-8859-1,utf-8;q=0.7,*;q=0.3"
HTTP_ACCEPT_ENCODING: "gzip, deflate"
HTTP_ACCEPT_LANGUAGE: "de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4"
HTTP_CACHE_CONTROL: "max-age=0"
REMOTE_ADDR: "31.19.213.6"
SERVER_NAME: "hackful.eu"
SERVER_PROTOCOL: "HTTP/1.1"

**Comment by 8bitpal** [comment]
Thanks, looking into it.
